apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix
spec:
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: ngnix:latest
      
        ports:
        - containerPort: 80
